name: 🌐 Deploy Awesome GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: 🎨 Build Modern Site
    runs-on: ubuntu-latest
    
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📊 Collect Data
        id: data
        run: |
          echo "commit_count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
          echo "last_commit=$(git log -1 --format='%h - %s (%cr)')" >> $GITHUB_OUTPUT
          echo "contributors=$(git log --format='%an' | sort -u | wc -l)" >> $GITHUB_OUTPUT
          echo "stars=$(curl -s https://api.github.com/repos/${{ github.repository }} | jq -r '.stargazers_count // 0')" >> $GITHUB_OUTPUT
          echo "build_date=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: 🎨 Generate Site
        run: |
          mkdir -p site
          cat > site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="zh-CN">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>RPA 自动化应用 | React Native 移动端解决方案</title>
            <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🤖</text></svg>">
            <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
            <style>
              :root {
                --primary: #6366f1;
                --primary-dark: #4338ca;
                --secondary: #06b6d4;
                --text: #1f2937;
                --text-light: #6b7280;
                --bg: #ffffff;
                --bg-secondary: #f8fafc;
                --shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
                --shadow-lg: 0 20px 25px -5px rgba(0, 0, 0, 0.1);
              }
              
              * { margin: 0; padding: 0; box-sizing: border-box; }
              
              body {
                font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
                line-height: 1.6;
                color: var(--text);
                background: var(--bg);
                overflow-x: hidden;
              }
              
              .animated-bg {
                position: fixed;
                top: 0; left: 0;
                width: 100%; height: 100%;
                z-index: -1;
                background: linear-gradient(-45deg, #667eea, #764ba2, #f093fb, #f5576c);
                background-size: 400% 400%;
                animation: gradientShift 15s ease infinite;
              }
              
              @keyframes gradientShift {
                0% { background-position: 0% 50%; }
                50% { background-position: 100% 50%; }
                100% { background-position: 0% 50%; }
              }
              
              .navbar {
                position: fixed;
                top: 0; width: 100%;
                padding: 1rem 2rem;
                z-index: 1000;
                transition: all 0.3s ease;
              }
              
              .navbar.scrolled {
                background: rgba(255, 255, 255, 0.95);
                backdrop-filter: blur(10px);
                box-shadow: var(--shadow);
              }
              
              .nav-content {
                max-width: 1200px;
                margin: 0 auto;
                display: flex;
                justify-content: space-between;
                align-items: center;
              }
              
              .logo {
                font-size: 1.5rem;
                font-weight: 700;
                color: var(--primary);
                text-decoration: none;
              }
              
              .nav-links {
                display: flex;
                gap: 2rem;
                list-style: none;
              }
              
              .nav-links a {
                color: var(--text);
                text-decoration: none;
                font-weight: 500;
                transition: color 0.3s ease;
              }
              
              .nav-links a:hover { color: var(--primary); }
              
              .container {
                max-width: 1200px;
                margin: 0 auto;
                padding: 0 2rem;
              }
              
              .hero {
                min-height: 100vh;
                display: flex;
                align-items: center;
                text-align: center;
                padding: 2rem 0;
              }
              
              .hero-content { width: 100%; }
              
              .hero h1 {
                font-size: clamp(2.5rem, 8vw, 4rem);
                font-weight: 700;
                margin-bottom: 1rem;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
              }
              
              .hero p {
                font-size: 1.25rem;
                color: var(--text-light);
                margin-bottom: 2rem;
                max-width: 600px;
                margin-left: auto;
                margin-right: auto;
              }
              
              .btn {
                display: inline-flex;
                align-items: center;
                gap: 0.5rem;
                padding: 1rem 2rem;
                border: none;
                border-radius: 12px;
                font-weight: 600;
                text-decoration: none;
                transition: all 0.3s ease;
                cursor: pointer;
              }
              
              .btn-primary {
                background: var(--primary);
                color: white;
                box-shadow: var(--shadow);
              }
              
              .btn-primary:hover {
                background: var(--primary-dark);
                transform: translateY(-2px);
                box-shadow: var(--shadow-lg);
              }
              
              .btn-secondary {
                background: transparent;
                color: var(--text);
                border: 2px solid #e5e7eb;
              }
              
              .btn-secondary:hover {
                background: var(--bg-secondary);
                transform: translateY(-2px);
              }
              
              .btn-group {
                display: flex;
                gap: 1rem;
                justify-content: center;
                flex-wrap: wrap;
              }
              
              .features {
                padding: 6rem 0;
                background: var(--bg-secondary);
              }
              
              .features-grid {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                gap: 2rem;
                margin-top: 3rem;
              }
              
              .feature-card {
                padding: 2rem;
                background: var(--bg);
                border-radius: 16px;
                box-shadow: var(--shadow);
                transition: all 0.3s ease;
                border: 1px solid #e5e7eb;
              }
              
              .feature-card:hover {
                transform: translateY(-4px);
                box-shadow: var(--shadow-lg);
              }
              
              .feature-icon {
                width: 60px; height: 60px;
                background: linear-gradient(135deg, var(--primary), var(--secondary));
                border-radius: 12px;
                display: flex;
                align-items: center;
                justify-content: center;
                color: white;
                font-size: 1.5rem;
                margin-bottom: 1rem;
              }
              
              .feature-card h3 {
                font-size: 1.25rem;
                margin-bottom: 0.5rem;
                color: var(--text);
              }
              
              .feature-card p {
                color: var(--text-light);
                line-height: 1.6;
              }
              
              .stats {
                padding: 4rem 0;
                text-align: center;
              }
              
              .stats-grid {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                gap: 2rem;
                margin-top: 2rem;
              }
              
              .stat-item { padding: 1.5rem; }
              
              .stat-number {
                font-size: 2.5rem;
                font-weight: 700;
                color: var(--primary);
                display: block;
              }
              
              .stat-label {
                color: var(--text-light);
                font-size: 0.9rem;
                text-transform: uppercase;
                letter-spacing: 0.5px;
              }
              
              .footer {
                background: var(--text);
                color: white;
                text-align: center;
                padding: 2rem 0;
              }
              
              .footer p { margin-bottom: 1rem; }
              
              .footer-links {
                display: flex;
                justify-content: center;
                gap: 2rem;
                margin-bottom: 1rem;
              }
              
              .footer-links a {
                color: white;
                text-decoration: none;
                opacity: 0.8;
                transition: opacity 0.3s ease;
              }
              
              .footer-links a:hover { opacity: 1; }
              
              @media (max-width: 768px) {
                .navbar { padding: 1rem; }
                .nav-links { display: none; }
                .container { padding: 0 1rem; }
                .btn-group {
                  flex-direction: column;
                  align-items: center;
                }
                .btn {
                  width: 100%;
                  max-width: 300px;
                }
                .footer-links {
                  flex-direction: column;
                  gap: 1rem;
                }
              }
              
              .fade-in {
                opacity: 0;
                transform: translateY(30px);
                transition: all 0.6s ease;
              }
              
              .fade-in.visible {
                opacity: 1;
                transform: translateY(0);
              }
              
              .loader {
                position: fixed;
                top: 0; left: 0;
                width: 100%; height: 100%;
                background: var(--bg);
                display: flex;
                justify-content: center;
                align-items: center;
                z-index: 9999;
                transition: opacity 0.5s ease;
              }
              
              .loader.hidden {
                opacity: 0;
                pointer-events: none;
              }
              
              .spinner {
                width: 40px; height: 40px;
                border: 4px solid #e5e7eb;
                border-top: 4px solid var(--primary);
                border-radius: 50%;
                animation: spin 1s linear infinite;
              }
              
              @keyframes spin {
                0% { transform: rotate(0deg); }
                100% { transform: rotate(360deg); }
              }
            </style>
          </head>
          <body>
            <div class="loader" id="loader">
              <div class="spinner"></div>
            </div>
            
            <div class="animated-bg"></div>
            
            <nav class="navbar" id="navbar">
              <div class="nav-content">
                <a href="#" class="logo">🤖 RPA App</a>
                <ul class="nav-links">
                  <li><a href="#features">功能特性</a></li>
                  <li><a href="#download">下载</a></li>
                  <li><a href="https://github.com/${{ github.repository }}">GitHub</a></li>
                </ul>
              </div>
            </nav>
            
            <section class="hero">
              <div class="container">
                <div class="hero-content fade-in">
                  <h1>React Native RPA 自动化应用</h1>
                  <p>强大的移动端UI自动化解决方案，支持脚本执行、远程控制和实时监控</p>
                  <div class="btn-group">
                    <a href="https://github.com/${{ github.repository }}/releases/latest" class="btn btn-primary">
                      <i class="fas fa-download"></i>
                      下载最新版本
                    </a>
                    <a href="https://github.com/${{ github.repository }}" class="btn btn-secondary">
                      <i class="fab fa-github"></i>
                      查看源码
                    </a>
                  </div>
                </div>
              </div>
            </section>
            
            <section class="features" id="features">
              <div class="container">
                <div class="fade-in">
                  <h2 style="text-align: center; font-size: 2.5rem; margin-bottom: 1rem;">功能特性</h2>
                  <p style="text-align: center; color: var(--text-light); font-size: 1.1rem;">为移动端自动化而生的强大功能</p>
                </div>
                
                <div class="features-grid">
                  <div class="feature-card fade-in">
                    <div class="feature-icon"><i class="fas fa-mobile-alt"></i></div>
                    <h3>UI 自动化</h3>
                    <p>支持 Android 设备的 UI 自动化操作，包括点击、滑动、输入等常用手势</p>
                  </div>
                  
                  <div class="feature-card fade-in">
                    <div class="feature-icon"><i class="fas fa-code"></i></div>
                    <h3>脚本执行</h3>
                    <p>支持 JavaScript 脚本远程执行，提供丰富的 API 接口和错误处理机制</p>
                  </div>
                  
                  <div class="feature-card fade-in">
                    <div class="feature-icon"><i class="fas fa-server"></i></div>
                    <h3>HTTP 服务</h3>
                    <p>内置 HTTP 服务器，支持远程控制和 Web 调试界面，方便开发测试</p>
                  </div>
                  
                  <div class="feature-card fade-in">
                    <div class="feature-icon"><i class="fas fa-shield-alt"></i></div>
                    <h3>系统权限</h3>
                    <p>支持系统设置访问、应用启动控制等高级权限操作</p>
                  </div>
                  
                  <div class="feature-card fade-in">
                    <div class="feature-icon"><i class="fas fa-bug"></i></div>
                    <h3>调试工具</h3>
                    <p>完整的调试工具链，包括日志查看、错误分析和性能监控</p>
                  </div>
                  
                  <div class="feature-card fade-in">
                    <div class="feature-icon"><i class="fas fa-rocket"></i></div>
                    <h3>高性能</h3>
                    <p>基于 React Native 构建，原生性能，流畅体验</p>
                  </div>
                </div>
              </div>
            </section>
            
            <section class="stats">
              <div class="container">
                <div class="fade-in">
                  <h2 style="font-size: 2.5rem; margin-bottom: 1rem;">项目数据</h2>
                  <p style="color: var(--text-light);">实时更新的项目统计信息</p>
                </div>
                
                <div class="stats-grid fade-in">
                  <div class="stat-item">
                    <span class="stat-number">${{ steps.data.outputs.commit_count }}</span>
                    <span class="stat-label">提交次数</span>
                  </div>
                  <div class="stat-item">
                    <span class="stat-number">${{ steps.data.outputs.contributors }}</span>
                    <span class="stat-label">贡献者</span>
                  </div>
                  <div class="stat-item">
                    <span class="stat-number">${{ steps.data.outputs.stars }}</span>
                    <span class="stat-label">GitHub Stars</span>
                  </div>
                  <div class="stat-item">
                    <span class="stat-number">Android</span>
                    <span class="stat-label">支持平台</span>
                  </div>
                </div>
              </div>
            </section>
            
            <footer class="footer">
              <div class="container">
                <div class="footer-links">
                  <a href="https://github.com/${{ github.repository }}/issues">问题反馈</a>
                  <a href="https://github.com/${{ github.repository }}/wiki">文档</a>
                  <a href="https://github.com/${{ github.repository }}/releases">发布历史</a>
                </div>
                <p>&copy; 2024 RPA 自动化应用. 构建时间: ${{ steps.data.outputs.build_date }}</p>
                <p style="opacity: 0.7; font-size: 0.9rem;">最后提交: ${{ steps.data.outputs.last_commit }}</p>
              </div>
            </footer>
            
            <script>
              window.addEventListener('load', function() {
                setTimeout(() => {
                  document.getElementById('loader').classList.add('hidden');
                }, 500);
              });
              
              window.addEventListener('scroll', function() {
                const navbar = document.getElementById('navbar');
                if (window.scrollY > 100) {
                  navbar.classList.add('scrolled');
                } else {
                  navbar.classList.remove('scrolled');
                }
              });
              
              const observerOptions = {
                threshold: 0.1,
                rootMargin: '0px 0px -50px 0px'
              };
              
              const observer = new IntersectionObserver(function(entries) {
                entries.forEach(entry => {
                  if (entry.isIntersecting) {
                    entry.target.classList.add('visible');
                  }
                });
              }, observerOptions);
              
              document.querySelectorAll('.fade-in').forEach(el => {
                observer.observe(el);
              });
              
              document.querySelectorAll('a[href^="#"]').forEach(anchor => {
                anchor.addEventListener('click', function (e) {
                  e.preventDefault();
                  const target = document.querySelector(this.getAttribute('href'));
                  if (target) {
                    target.scrollIntoView({
                      behavior: 'smooth',
                      block: 'start'
                    });
                  }
                });
              });
            </script>
          </body>
          </html>
          EOF

      - name: 📄 Setup Pages
        uses: actions/configure-pages@v4

      - name: 📤 Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    name: 🚀 Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: 🌐 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 